### ISSUE TITLE
I can't get it to work on the server

### ISSUE THREAD

**Issue by cosio55** [percolatestudio/meteor-segment.io#40]
Hi, I would like to know if anyone has been able to use this amazing package on the server, I already tried running it using two different calls:

```
				analytics.track({
					userId: Meteor.userId(),
					event: 'Added Product',
					properties: {
						id: producto._id,
						sku: producto._id,
						name: producto.nombre,
						price: producto.precio,
						quantity: cantidadProducto,
					}
				});
```

and 

```
analytics.track('Added Product', {
					id: producto._id,
					sku: producto._id,
					name: producto.nombre,
					price: producto.precio,
					quantity: cantidadProducto,
					category: categoria.nombre
				});
```

but with both of them I get the same error:

`Exception while invoking method 'sumarProducto' { stack: 'TypeError: Object [object Object] has no method \'track\'\n    at [object Object].Meteor.methods.actualizarStock (server/metodosCarritoUsuario.js:121:15)\n    at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:164:1)\n    at maybeAuditArgumentChecks (livedata_server.js:1698:12)\n    at livedata_server.js:1611:18\n    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)\n    at [object Object]._.extend.apply (livedata_server.js:1610:45)\n    at [object Object]._.extend.call (livedata_server.js:1553:17)\n    at [object Object].Meteor.methods.sumarProducto (server/metodosCarritoUsuario.js:59:10)\n    at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:164:1)\n    at maybeAuditArgumentChecks (livedata_server.js:1698:12)',`

Is there anything I'm doing wrong? 

Thanks in advance.

**Comment by mitiaptest** [comment]
+ Same issue but if you add analytics.load('YOUR_WRITE_KEY') then its working. Do we really need to configure client and server both ?
